### ISSUE TITLE
Potentially unexpected behavior from "HTML escaped" characters

### ISSUE THREAD

**Issue by Xortrox** [MTobisch/ngx-dynamic-hooks#12]
I could be missing something, or an option somewhere that allows me to specify the behavior, but I noticed that for instance &lt; and &gt; gets treated as actual < and >  when passed into the [content] input:
![image](https://i.imgur.com/hfNYleI.png)

This behavior is unexpected because it would allow a user to manually send in our <app-item-link> tag in chat, despite this being HTML-escaped server side

**Comment by Xortrox** [comment]
After posting this I realized there exists a global option called "convertHTMLEntities" but even with this turned off, the problem persists.

**Comment by Xortrox** [comment]
![image](https://user-images.githubusercontent.com/5203005/148028674-89d46c97-1f45-4007-b624-883f9a6e331b.png)
This shows how we implement our module in all cases^

And this would be our global options object:
![image](https://i.imgur.com/ZLHbiar.png)

**Comment by Xortrox** [comment]
![image](https://user-images.githubusercontent.com/5203005/148029211-e4d437f9-8827-4c46-837f-271cca269e46.png)
Our <ngx-dynamic-hooks> element was potentially overriding the global options^ investigating

**Comment by Xortrox** [comment]
Yes, nevermind then, this was why the option did not work, and it now works as expected:
![image](https://user-images.githubusercontent.com/5203005/148029472-d064cf8c-1ab9-4355-8b80-888bf92d52c9.png)

I still think that this being the default behavior is unexpected?

**Comment by MTobisch** [comment]
I'm sorry this has caused some confusion for you. 

Honestly, I added the conversion of HTML chars by default as a sort of convenience feature for certain scenarios, such as for example using your Angular hooks in a WYSIWYG editor that might escape the input before saving it in a database. I didn't want devs to deal with also finding a good way to convert HTML entities in addition to understanding my library. Its a minor nuisance. This way, it simply works out of the box in more use cases.

I left it as the default option because I figured unintentional escaping might be more common than intentional escaping (as with your game). But yeah, its hard to make that call.

**Comment by Xortrox** [comment]
Very understandable, could it be an idea to address this specific special case in the documentation to some extent? It's one of those things a few developers might miss or not think about, causing unintended behavior in my experience, generally speaking for HTML escaping that is.

**Comment by MTobisch** [comment]
You may be right. I've added a paragraph addressing the issue in the troubleshooting FAQ in the documentation.
