### ISSUE TITLE
formControl supporting?

### ISSUE THREAD

**Issue by hhiliahh** [MTobisch/ngx-dynamic-hooks#17]
I have some code like this:
`<textbox [formControl]='context.formControl'></textbox>`
and my context object:
`contextObj = {
		name: 'Kenobi',
		formControl: new FormControl("hello"),
	}`
but it does not work, where did I go wrong?

**Comment by MTobisch** [comment]
Hey there again,

could you elaborate a bit? Is `<textbox>` an Angular component? And if it is, could you check what kind of value arrives inside of it as `this.formControl`?

It generally shouldn't matter what kind of data you use in the context object as its just passed along. So FormControls, too, should be fine.

**Comment by hhiliahh** [comment]
Hello again,
Yes, textbox is an angular NgValueAccessor component and accept string value.
When move this code to  html template and bind it to formControl, it work correctly.

ts file:
`let contextObj = { name: 'Kenobi', formControl: new FormControl("hello"), }`
`let template='<kendo-textbox [formControl]='context.formControl'></kendo-textbox>';`

html file:

this is not work:
`<ngx-dynamic-hooks [content]="template" [context]="contextObj"></ngx-dynamic-hooks>`

but this line worked correctly:
`<kendo-textbox [formControl]='contextObj.formControl'></kendo-textbox>`

**Comment by MTobisch** [comment]
As I little knowledge about Kendo UI (or NgValueAccessor components at that), its difficult to determine the inner workings of `<kendo-textbox>` and why it doesn't work. 

However, I suspect its because `[formControl]`  is actually used as a directive here rather than as an input for a component. And using directives in the `content` input for `<ngx-dynamic-hooks>` [is not supported](https://github.com/MTobisch/ngx-dynamic-hooks#93-caveats). The library is only able to load components from dynamic strings.

However, you may be able to circumvent this restriction by simply wrapping `<kendo-textbox>` in another placeholder component and using the directive there instead of the content string directly. Then it should work again. Like so:

ts:
`let contextObj = { name: 'Kenobi', formControl: new FormControl("hello"), }`
`let template="... <app-mywrapper [myFormControl]='context.formControl'></app-mywrapper> ...";`

with

`<ngx-dynamic-hooks [content]="template" [context]="contextObj"></ngx-dynamic-hooks>`

Then write MyWrapperComponent as something like:
```
@Component({
  selector: 'app-mywrapper',
  template: '<kendo-textbox [formControl]='myFormControl'></kendo-textbox>'
})
class MyWrapperComponent {
   @Input() myFormControl: FormControl;
}
```

**Comment by hhiliahh** [comment]
Thank you very much, your proposed method is interesting, but it is not possible.
