### ISSUE TITLE
forChild support

### ISSUE THREAD

**Issue by fleskberg** [MTobisch/ngx-dynamic-hooks#18]
Hi! Really like the the dynamic hook feature.
In my project I would like to be able do define the different components for in different modules. Not every component in main module (forRoot). So it´s kind of a improvement suggestion.

**Comment by MTobisch** [comment]
It has been a while since this has been requested, but I've finally come around to adding forChild()-support for both eagerly- and lazily-loaded child modules!

If you like, you can check it out in the new versions:

**Angular <13:** ngx-dynamic-hooks 1.8.0
**Angular 13+:** ngx-dynamic-hooks 2.1.0

See also the new [forChild()-chapter of the documentation](https://github.com/MTobisch/ngx-dynamic-hooks#65-child-modules-forchild).
