### ISSUE TITLE
Cannot npm install for angular 12.2.16

### ISSUE THREAD

**Issue by glickid** [MTobisch/ngx-dynamic-hooks#19]
Hello, 

Would like to use ngx-dynamic-hooks with angular 12 .2.16

When trying to install ngx-dynamic-hooks@^1.0.0 I get following error - 

![image](https://user-images.githubusercontent.com/13085800/166150694-0a57005e-c778-493e-952f-fa65316a7a69.png)

When trying to install ngx-dynamic-hooks@^2.0.0 I get following error - 

![image](https://user-images.githubusercontent.com/13085800/166150717-0db59659-4396-4d3c-b266-7626862918d8.png)

Please, advise

**Comment by MTobisch** [comment]
Huh, this is weird. The problem here is that when executing `ngx-dynamic-hooks@^1.0.0`, npm is installing v.1.0.0 exactly, instead of v1.7.2 which it should (and would work with Angular 12).  I'm not sure I understand why it does this.

This behaviour only seems to occur when calling `npm install library@version` directly. If you instead manually add `dynamic-hooks: "^1.0.0"` as a dependency to your _package.json_ and simply call `npm install`, it will work and correctly download v1.7.2. 

**Note:** If you have already installed the wrong version, make sure to delete your _package-lock.json_ and the _ngx-dynamic-hooks_-folder from _node_modules_ first for a clean reinstall, however.

**Comment by glickid** [comment]
Thanks MTobisch, I have manually added "ngx-dynamic-hooks": "^1.7.2" to package.json and npm install completed successfully
