### ISSUE TITLE
Getting Function calls are not supported in decorators but 'DynamicHooksModule' was called. when I run ng build --prod

### ISSUE THREAD

**Issue by ss94866** [MTobisch/ngx-dynamic-hooks#32]
I am using angular 7 application. using "ngx-dynamic-hooks": "^1.8.0"

ERROR in Error during template compile of 'SharedModule'
  Function calls are not supported in decorators but 'DynamicHooksModule' was called.

Everything works fine in local. The only thing is I cant able to make the prod build of my angular7 application. 
I didn't get any error on running npm start or ng build. But when I run with --prod flag (ng build --prod). I am getting above error

![image](https://github.com/MTobisch/ngx-dynamic-hooks/assets/68229944/b4d892a6-ab2e-4063-9603-79a82ea04a1f)

**Comment by MTobisch** [comment]
Hey there, thanks for the bug report!

I've hopefully just released a fix with **v1.8.1**. Can you try it out and tell me if it compiles fine now (for prod)?

It seems this had to do with an issue introduced in v1.8.0. The View Engine AOT compiler really doesn't like any logic in forRoot(). Unfortunately, due to those restrictions, the forChild-features of this library won't work with the old compiler in AOT (prod) mode. I hope this doesn't affect you.

**Comment by ss94866** [comment]
Thank you for the support.
