### ISSUE TITLE
can we do a small update to angular 16 to solve the universal flickering?

### ISSUE THREAD

**Issue by hiepxanh** [MTobisch/ngx-dynamic-hooks#36]
https://github.com/angular/angular/issues/51318
Hi, I'm working on angular universal and the new angular core version seem very useful to fix the flickering on server side rendering. Can you do a small update once they release a new one? or I'm willing to do a PR if you want me to try that @MTobisch

**Comment by MTobisch** [comment]
Hey there,

generally speaking, while it is true that the library is built with the Angular 13 library tools, the actually resulting code (that then exists in your node_modules folder) should work with newer Angular versions as well. This is because it doesn't contain any Angular code and simply imports it like so `import X '@angular/core'` from your project. In other words, if your project uses Angular 16 core, the library will as well. So theoretically, whatever fixes are patched into "@angular/core" should work for the library too.

Disclaimer: I haven't tested the library specially with Angular 16 yet (but 15 worked fine).

So have you yet tested the new fix / core version in combination with the library? The last fix seemed to work immediately as I understand it.

**Overall**, the flicker bug is kind of a complex issue and I'm having a difficult time understanding why it happens with my library as both issues [#51157](https://github.com/angular/angular/issues/51157) and [#51318](https://github.com/angular/angular/issues/51318) relate to using `ViewContainerRef.createComponent` and my library doesn't do that or even use ViewContainerRefs in general.

In simplified terms, the library does this for every dynamic component:

```
  const containerElement = this.renderer.createElement("app-dynamiccomponent");
  const dynamicComponentFactory = this.cfr.resolveComponentFactory(DynamicComponentClass);
  const dynamicComponentRef = dynamicComponentFactory.create(injector, [], containerElement);
  this.appRef.attachView(dynamicComponentRef.hostView);
  dynamicComponentRef.changeDetectorRef.detectChanges();
```
Most of this code can be found in [ComponentCreator.createComponent](https://github.com/MTobisch/ngx-dynamic-hooks/blob/master/projects/ngx-dynamic-hooks/src/lib/components/outlet/services/componentCreator.ts#L325).

I'm unsure if this logic somehow circumvents the new hydration logic of Angular 16, which then causes Angular to instead recreate the dynamic components on the client from scratch instead of properly hydrating them, causing the flicker.

**Comment by hiepxanh** [comment]
thank you so much. I already view your file before create that issue. So if that lib using current angular version in the repo. I think must be something else I'm missing. And I was though that resolveComponentFactory do the same thing with viewContainerRef. Look like they have different way to work so we get different result. I will try some more test and get notice to you about my process. I also try to make some test to reproduce it too

**Comment by hiepxanh** [comment]
close issue since I have to rewrite it to make it work with Universal
