### ISSUE TITLE
Problem passing object arrays to inputs

### ISSUE THREAD

**Issue by LighthouseKrakenDSM** [MTobisch/ngx-dynamic-hooks#37]
I'm having a problem passing in an object array to dynamically generated component. I have modal component that has the dynamic hook installed. I have a dropdown component referenced using `componentParsers: Array<HookParserEntry>` and I added the module of that component to the imports. 

In my example code I provided, I'm passing in a template for the modal body. Within that template is the Angular dropdown component. The dropdown component renders fine however, the dropdown has an "items" and "fields" property that require an object array.  I'm having problems setting this data. I've tried passing it in through a template literal like this with no luck.  

`[fields]="${modalfields}"`
`[items]="${modalitems}"`

Then I tried the example below where I bind to the dropdown component after its rendered in the Dom, but even with this example I'm not able to get the data to render. 
These properties on the component  render fine, just not the "fields" and "items"

`[label]="'Country'" `
`[placeholder]="'Choose a country'"`

Also, I'm not able to set an "id" on anything inside the template. The id doesn't render in the dom. I'm lost at this point. Do you have any ideas on how I can accomplish this?

Here is the code:

**html**
`<kn-web-modal id="exampleModal" modal-id="myModal" title="Kraken Modal"></kn-web-modal>`

**javascript**
`let modal = document.querySelector('#exampleModal');`
`modal.content = `
`"<div class="dropdown">`
`   <kn-dropdown  `
`      [label]="'Country'"`
`      [placeholder]="'Choose a country'"` 
`      [name]="'exampledropdown'">`
`   </kn-dropdown>`
`</div>"`
		  
`let modalDropdownParent = document.querySelector(".dropdown");`
`const modalDropdown = modalDropdownParent.firstElementChild`
`modalDropdown.value = "United States";`
`modalDropdown.fields = {text: 'country', value: 'code'};`
`modalDropdown.items = [`
`  {country:'United States', id: '+0', code: 'US'}, `
`  {country:'Canada', id: '+1', code: 'CA'}, `
`  {country:'Germany', id: '+49', code: 'DE', disabled: true}`
`];`

**Comment by MTobisch** [comment]
From your descriptions, I'm a bit confused as to whether you are using normal Angular and tried to imperatively bind inputs as a last resort or if you are using Angular Elements, since it would look pretty similar to this. Hopefully, it makes no difference for your problem. I'm assuming that the `content` property of your modal component is passed directly to the library like so: `<ngx-dynamic-hooks [content]="content">`?

Based on that assumption, the problem might simply be that `[fields]="${modalfields}"` doesn't print the array in a simple enough format so it can be parsed again properly. If it was something like `[fields]="['firstField', 'secondField', 'thirdField']"` (as you would write it in code), it should be picked up just like the other inputs.

Alternatively, the better way of passing variables to your dynamic components is using the `context` input, as that bypasses making everything a string first. Put everything you need in there and pass it along. Very generally, this could look like so:

**Code:**
```
let context = {
  fields: modalfields,
  items: modalitems
};

let content = `
<div class="dropdown">
  <kn-dropdown 
      [label]="'Country'"
      [placeholder]="'Choose a country'"
      [name]="'exampledropdown'">
      [fields]="context.fields"
      [items]="context.items"
   </kn-dropdown>
</div>`;
```

**modal.html**
```
<ngx-dynamic-hooks [content]="content" [context]="context"></ngx-dynamic-hooks>
```

As for the id attribute disappearing, that's very likely caused by [Angular's sanitization](https://stackoverflow.com/questions/57400432/angular-how-to-retain-html-id-attribute-when-sanitized), which is enabled by default for security reasons. You can disable it via the [OutletOptions](https://github.com/MTobisch/ngx-dynamic-hooks#64-outletoptions), for example like so:

```
<ngx-dynamic-hooks [content]="content" [context]="context" [options]="{sanitize: false}"></ngx-dynamic-hooks>
```

**Comment by LighthouseKrakenDSM** [comment]
Thanks for  the help! That worked using context!

Any idea why I'm not able to add id's to any elements inside the modal template? For instance, the following code does not render with the `id="dropdownContainerId"` on the element as shown:

`let content =`\`
`<div class="dropdown" id="dropdownContainerId">`
`   <kn-dropdown` 
`      [label]="'Country'"`
`      [placeholder]="'Choose a country'"`
`      [name]="'exampledropdown'">`
`      [fields]="context.fields"`
`      [items]="context.items"`
`   </kn-dropdown>`
`</div>`\`;

**Comment by MTobisch** [comment]
Sure, i mentioned it at the very end of my last comment. You probably didn't see it!

**Comment by LighthouseKrakenDSM** [comment]
Yep, i miss it lol! Thank you for the quick response. This has save me so much time and hassle.
